# vim: set ft=bash :

# Are we on a Mac?
if [[ "$HOME" =~ /Users/* ]]; then
    JPMELOS_IS_MACOS="true"
else
    JPMELOS_IS_MACOS="false"
fi

# Set the PATH. Things are always prepended, so the last entry to be entered
# here is the one with the highest priority.
# Binaries installed by Homebrew.
if [[ $JPMELOS_IS_MACOS == "true" ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi
# Rust tooling's own binaries.
export PATH="$HOME/.cargo/bin:$PATH"
# pyenv's own binaries.
export PATH="$HOME/.pyenv/bin:$PATH"
# Binaries not managed via a package manager.
export PATH="$HOME/.local/bin:$PATH"
# My own executables.
export PATH="$HOME/bin:$PATH"

# Sets the default editor for various commands.
export EDITOR=$(which nvim)

# Find any custom terminfos that we install.
export TERMINFO_DIRS=$HOME/.local/share/terminfo:$TERMINFO_DIRS
# For better colors in Neovim.
export TERM=tmux-256color

#############################
#                           #
#    Bash-specific stuff    #
#                           #
#############################

# Keep infinite command history in memory.
export HISTSIZE=-1
# Erase all duplicate lines, don't store lines starting with space.
export HISTCONTROL=erasedups:ignoreboth
# Keep infinite command history in file.
export HISTFILESIZE=-1
# Persist every command immediately, load new commands.
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"

###############################
#                             #
#    Python-specific stuff    #
#                             #
###############################

# Make Pip require a virtual environment to install stuff. Do not pollute
# the system.
export PIP_REQUIRE_VIRTUALENV=true

# No need to show the current virtual environment in the prompt, since we'll
# use Starship for that.
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Indicate where the pyenv root is.
export PYENV_ROOT=$HOME/.pyenv

##########################
#                        #
#    Source ~/.bashrc    #
#                        #
##########################

source ~/.bashrc
