default_profile = ""

[theme]
name = "catppuccin-latte"

[updates]
check_enabled = false

[worktree]
enabled = false

[sandbox]
enabled_by_default = false

[tmux]
status_bar = "disabled"
mouse = "disabled"

[session]
default_tool = "claude"

[sound]
enabled = true
# on_start = "coins.wav"
# on_running = "coins.wav"
on_waiting = "coins.wav"
on_idle = "coins.wav"
on_error = "coins.wav"

[sound.mode]
specific = ""

[app_state]
has_seen_welcome = true
last_seen_version = "0.15.1"
has_seen_custom_instruction_warning = false
