#!/bin/bash

mv ~/.bash_profile ~/.bash_profile_bkp
cp bash_profile ~/.bash_profile

mv ~/.bashrc ~/.bashrc_bkp
cp bashrc ~/.bashrc

mv ~/.gitconfig ~/.gitconfig_bkp
cp gitconfig ~/.gitconfig

mv ~/.vimperatorrc ~/.vimperatorrc_bkp
cp vimperatorrc ~/.vimperatorrc

mv ~/.vimrc ~/.vimrc_bkp
cp vimrc ~/.vimrc

mv ~/.Xdefaults ~/.Xdefaults_bkp
cp Xdefaults ~/.Xdefaults

mv ~/.xinitrc ~/.xinitrc_bkp
cp xinitrc ~/.xinitrc

mv ~/.config/openbox/autostart.sh ~/.config/openbox/autostart.sh_bkp
cp config/openbox/autostart.sh ~/.config/openbox/autostart.sh

mv ~/.config/openbox/menu.xml ~/.config/openbox/menu.xml_bkp
cp config/openbox/menu.xml ~/.config/openbox/menu.xml

mv ~/.config/openbox/rc.xml ~/.config/openbox/rc.xml_bkp
cp config/openbox/rc.xml ~/.config/openbox/rc.xml

mv ~/.tmux.conf ~/.tmux.conf_bkp
cp tmux.conf ~/.tmux.conf

mv ~/.rtorrent.rc ~/.rtorrent.rc_bkp
cp rtorrent.rc ~/.rtorrent.rc
